import { AuthProvider } from '@/context/AuthContext'
import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '@/components/navBar/navBar'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Reproductor',
  description: 'Generated by Timberli',
} 

export default function RootLayout({ children }) {

  return (
    <html lang="en">  
      <body className={inter.className}>
      <AuthProvider>
        <NavBar/>
        {children}
      </AuthProvider>
      </body>
    </html>
  )
}
